import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./navbar/page";
import Footer from "./Components/footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GHAZIANI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav/>
        {children}
        <Footer/>
        <p><a href="https://www.linkedin.com/in/noman-ghaziani-7a9439288/">
<button className="flex mx-auto mt-10 text-white bg-blue-400">Visit My Linkedin</button>
</a></p>
      </body>
    </html>
  );
}
